#!/bin/bash
docker exec -it jd bash jd jd_bean_change now
docker exec -it jd bash jd jd_bean_home now
docker exec -it jd bash jd jd_bean_sign now
docker exec -it jd bash jd jd_blueCoin now
docker exec -it jd bash jd jd_bookshop now
docker exec -it jd bash jd jd_car now
docker exec -it jd bash jd jd_car_exchange now
docker exec -it jd bash jd jd_cash now
docker exec -it jd bash jd jd_club_lottery now
docker exec -it jd bash jd jd_crazy_joy now
docker exec -it jd bash jd jd_crazy_joy_coin now
docker exec -it jd bash jd jd_daily_egg now
docker exec -it jd bash jd jd_dreamFactory now
docker exec -it jd bash jd jd_family now
docker exec -it jd bash jd jd_firecracker now
docker exec -it jd bash jd jd_fruit now
docker exec -it jd bash jd jd_get_share_code now
docker exec -it jd bash jd jd_gyec now
docker exec -it jd bash jd jd_immortal now
docker exec -it jd bash jd jd_jdfactory now
docker exec -it jd bash jd jd_jdzz now
docker exec -it jd bash jd jd_joy now
docker exec -it jd bash jd jd_joy_feedPet now
docker exec -it jd bash jd jd_joy_help now
docker exec -it jd bash jd jd_joy_reward now
docker exec -it jd bash jd jd_joy_run now
docker exec -it jd bash jd jd_joy_steal now
docker exec -it jd bash jd jd_joy_treasure_spider now
docker exec -it jd bash jd jd_jxnc now
docker exec -it jd bash jd jd_kd now
docker exec -it jd bash jd jd_live now
docker exec -it jd bash jd jd_live_redrain now
docker exec -it jd bash jd jd_live_redrain2 now
docker exec -it jd bash jd jd_live_redrain_half now
docker exec -it jd bash jd jd_live_redrain_nian now
docker exec -it jd bash jd jd_live_redrain_offical now
docker exec -it jd bash jd jd_lotteryMachine now
docker exec -it jd bash jd jd_mh now
docker exec -it jd bash jd jd_mh_super now
docker exec -it jd bash jd jd_moneyTree now
docker exec -it jd bash jd jd_necklace now
docker exec -it jd bash jd jd_nh now
docker exec -it jd bash jd jd_nian now
docker exec -it jd bash jd jd_nianCollect now
docker exec -it jd bash jd jd_nian_sign now
docker exec -it jd bash jd jd_pet now
docker exec -it jd bash jd jd_petTreasureBox now
docker exec -it jd bash jd jd_pigPet now
docker exec -it jd bash jd jd_plantBean now
docker exec -it jd bash jd jd_rankingList now
docker exec -it jd bash jd jd_redPacket now
docker exec -it jd bash jd jd_shop now
docker exec -it jd bash jd jd_small_home now
docker exec -it jd bash jd jd_speed now
docker exec -it jd bash jd jd_superMarket now
docker exec -it jd bash jd jd_super_coupon now
docker exec -it jd bash jd jd_sx now
docker exec -it jd bash jd jd_sy now
docker exec -it jd bash jd jd_unbind now
docker exec -it jd bash jd jd_unsubscribe now
docker exec -it jd bash jd jd_vote now
docker exec -it jd bash jd jd_wechat_sign now
docker exec -it jd bash jd jd_xg now
docker exec -it jd bash jd jd_xxl now
docker exec -it jd bash jd jd_xxl_gh now
docker exec -it jd bash jd jx_sign now
